=== PetitSamuel/college/year2/Information_Management_I/xml xquery files/driver.dtd
<!ELEMENT Driver (person*)>
<!-- there can be none, one, or multiple drivers in the class -->

<!ELEMENT person (personalInfo,penaltyPoints,contactDetails)>
<!ATTLIST person age CDATA #IMPLIED>
<!ATTLIST Driver idNumber CDATA #IMPLIED>

<!ELEMENT personalInfo (firstName,lastName,DOB)>
<!-- a driver has to provide one and only one value for each -->
<!ELEMENT penaltyPoints (#PCDATA)>

<!ELEMENT contactDetails (phoneNumber+,email+)>
<!-- a driver has to provide one phone number, but may provide more, same for the email -->

<!--  every driver has a first name, last name, date of birth (DOB), a phone number & email -->
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT DOB (#PCDATA)>
<!ELEMENT phoneNumber (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== PetitSamuel/college/year2/Information_Management_I/xml xquery files/driver.xml
<?xml version="1.0"?>
<!DOCTYPE Driver SYSTEM "driver.dtd">
<Driver idNumber='1234567'>
  <person age='45'>
	  <personalInfo>
		<firstName>John</firstName>
		<lastName>Doe</lastName>
		<DOB>05/06/1973</DOB>
	  </personalInfo>
	  <penaltyPoints>69</penaltyPoints>
	  <contactDetails> 
		  <phoneNumber>123456789</phoneNumber>
		  <email>johndoe@gmail.com</email>
	  </contactDetails>
  </person> 
</Driver>
