=== PetitSamuel/college/year2/CS2041 - Information Management I/project/xml xquery files/claim.dtd
<!DOCTYPE claim [

<!ELEMENT claim (type,privateInformation*)>

<!ELEMENT claim type CDATA #REQUIRED

<!ELEMENT privateInformation (name,synopsis,driverName*,driverID,thirdPartyInsurer)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT synopsis (#PCDATA)>

<!ELEMENT driverName ( title,firstName,surname)>

<!ELEMENT title (#PCDATA)>

<!ELEMENT firstName (#PCDATA)>

<!ELEMENT surname (#PCDATA)>

<!ELEMENT driverID (ID)>

<!ELEMENT thirdPartyInsurer (#PCDATA)>

]>

=== PetitSamuel/college/year2/CS2041 - Information Management I/project/xml xquery files/claim.xml
<?xmlversion = "1.0"?>
<!DOCTYPE claim SYSTEM "claim.dtd">
<claim type ="3">
  <privateInformation>
    <name> Crash </name>
    <synopsis>
      "Third party driver drove into the 
      back of claimant's vehicle on the 3rd November"</synopsis>
      <driverName>
        <title>Mr.</title>
        <firstName>John</firstName>
        <surname>Doe</surname>
      </driverName>
      <driverID>1234567</driverID>
      <thirdPartyInsurer>AXA</thirdPartyInsurer>
  </privateInformation>
</claim>
