=== PetitSamuel/college/year2/CS2041 - Information Management I/project/xml xquery files/policyDTD.dtd
<!DOCTYPE Policy [
<!ELEMENT policy (customer*)>
<!ATTLIST policy type CDATA #IMPLIED>

<!ELEMENT customer(personalInfo,contactDetails,policyInfo)>
<!ATTLIST customer idNumber CDATA #IMPLIED>

<!ELEMENT personalInfo(firstName,lastName,DOB,penaltyPoints)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT DOB (#PCDATA)>
<!ELEMENT penaltyPoint (#PCDATA)>

<!ELEMENT contactDetails(phoneNumber,email)>
<!ELEMENT phoneNumber(#PCDATA)>
<!ELEMENT email(#PCDATA)>

<!ELEMENT policyInfo (cover,startDate,endDate)>
<!ATTLIST policyInfo id CDATA #IMPLIED>
<!ELEMENT cover (#PCDATA)>
<!ELEMENT startDate (#PCDATA)>
<!ELEMENT endDate (#PCDATA)>

]>

=== PetitSamuel/college/year2/Information_Management_I/project/xml xquery files/policy.xml
<?xml version="1.0"?>
<!DOCTYPE Policy SYSTEM "policyDTD.dtd"> 

  <policy type="car insurance">
    <customer idNumber="1234567">
      <personalInfo>
        <firstName>John</firstName>
        <lastName>Doe</lastName>  
        <DOB>1973-05-06</DOB>
        <penaltyPoints>69</penaltyPoints>
      </personalInfo>
      <contactDetails>
        <phoneNumber>123456789</phoneNumber>
        <email>johndoe@gmail.com</email>
      </contactDetails>
      <policyInfo id="5989">
        <cover>third party</cover>
        <startDate>2018-11-15</startDate>
        <endDate>2019-11-19</endDate>
      </policyInfo>
    </customer> 
  </policy>
