=== PetitSamuel/college/year2/CS2041 - Information Management I/project/xml xquery files/quoteSystem.dtd
<!DOCTYPE quoteSystem [

<!ELEMENT quoteSystem (website,input*)>

<!ELEMENT website (#PCDATA)>

<!ELEMENT input (vehicle,registration,driver*)>

<!ELEMENT vehicle (#PCDATA)>

<!ELEMENT registration (#PCDATA)>

<!ELEMENT driver (name*,dateOfBirth,firstReceivedLicense)>

<!ELEMENT name (title, firstName, surname)>

<!ELEMENT title (#PCDATA)>

<!ELEMENT firstName (#PCDATA)>

<!ELEMENT surname (#PCDATA)>

<!ELEMENT dateOfBirth (#PCDATA)>

<!ELEMENT firstReceivedLicense (#PCDATA)>

]>

=== PetitSamuel/college/year2/Information_Management_I/project/xml xquery files/quoteSystem.xml
<?xmlversion = "1.0"?>
<!DOCTYPE quoteSystem SYSTEM "quoteSystem.dtd">
<quoteSystem>
  <website>"https://www.axa.ie"</website>
  <input>
    <vehicle>"Opel Corsa"</vehicle>
    <registration>"03-D-3434"</registration>
    <driver>
      <name>
        <title>Mr.</title>
        <firstName>John</firstName>
        <surname>Doe</surname>
      </name>
      <dateOfBirth>01/01/1996</dateOfBirth>
      <firstReceivedLicense>04/12/2017</firstReceivedLicense>
    </driver>
  </input>
</quoteSystem>
